### ISSUE TITLE
Gmail disconnects randomly, client can not be reused

### ISSUE THREAD

**Issue by jackdaddy69** [andris9/imapflow#15]
This is a suggestion as much as it is a bug, but here it goes:

When Gmail closes a connection randomly even though I am IDLEing, that is fine.  I get a close event.

The problem is when I try to then client.connect() immediately or after 10 seconds, the client object must have some old connection data in it and I receive:

08:39:54/Error: {"err":{"code":"ERR_STREAM_WRITE_AFTER_END"},"cid":"xxxxx"}
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:271:14)
    at ImapStream.Writable.write (_stream_writable.js:320:5)
    at TLSSocket.ondata (_stream_readable.js:708:22)
    at TLSSocket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at TLSSocket.Readable.push (_stream_readable.js:214:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
Emitted 'error' event on ImapFlow instance at:
    at ImapStream.<anonymous> (/home/jschoof/FTP/CCServer/CarCords/node_modules/imapflow/lib/imap-flow.js:247:18)
    at ImapStream.emit (events.js:333:22)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at writeAfterEnd (_stream_writable.js:273:3)
    at ImapStream.Writable.write (_stream_writable.js:320:5)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (_stream_readable.js:214:10) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

I have compression disabled...

So my solution has been to rebuild the client object from scratch with another client = new ImapFlow so that client is fresh.  Is this the way you wanted it to work andris9?  Maybe your client.connect() code could make sure the client object is "clean" so it is fresh and ready for another client.connect() after an unknown close?  Just a suggestion.

Great Library!  Thanks so much!  I'm using this to receive text commands, that are turned into email,  through google IMAP, parsed and then sent to our new Electric Vehicle Charging Stations so they can be controlled and managed through texts as well as web apps.  Some people can text but have no or limited data connectivity.  Your ImapFlow will be mission critical!

**Comment by andris9** [comment]
ImapFLow is built in way where the client is not reusable. Once it closes, it is done, you have to create a new ImapFlow object to connect to the server.

IMAP connections always include some state, for example what is the currently opened mailbox, what was the last known UIDNext or Modseq value etc. Once connection is closed you can not rely on the old information anymore, you have to start from scratch. ImapFlow is mainly built for [IMAP API](https://imapapi.com/) (or extracted from there to be a standalone library) and I have all reconnection logic in the IMAP API side, not in ImapFlow.
