### ISSUE TITLE
unexpected end of file error when logout called

### ISSUE THREAD

**Issue by Desmodue** [andris9/imapflow#22]
Node v10.16.3
OS Linux

When calling 
await client.logout();
I am using the example code.
This error is thrown, included other messages prior, to show logout is successful.

{"level":20,"time":1594996301712,"pid":3454774,"hostname":"xxxx","component":"imap-connection","cid":"1a9wjst60odltvjz1a4p","src":"s","msg":"A OK LOGOUT completed","cid":"1a9wjst60odltvjz1a4p"}

{"level":50,"time":1594996301713,"pid":3454774,"hostname":"xxxx","component":"imap-connection","cid":"1a9wjst60odltvjz1a4p","err":{"type":"Error","message":"unexpected end of file","stack":"Error: unexpected end of file\n    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)","errno":-5,"code":"Z_BUF_ERROR"},"cid":"1a9wjst60odltvjz1a4p"}
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)
Emitted 'error' event at:
    at ImapStream.ImapFlow.streamer.on.err (/.../node_modules/imapflow/lib/imap-flow.js:247:18)
    at ImapStream.emit (events.js:203:15)
    at InflateRaw._inflate.on.err (/.../node_modules/imapflow/lib/imap-flow.js:584:27)
    at InflateRaw.emit (events.js:198:13)
    at Zlib.zlibOnError [as onerror] (zlib.js:165:8)

**Comment by andris9** [comment]
I think that this should be fixed by now
