### ISSUE TITLE
mainLogger[level] is not a function

### ISSUE THREAD

**Issue by jhmen** [andris9/imapflow#23]
**Describe the bug**
When I use a custom logger with the methods debug(obj), info(obj), warn(obj) and error(obj) than this error is thrown:
```
TypeError: mainLogger[level] is not a function
    at Object.synteticLogger.<computed> [as info] (node_modules/imapflow/lib/imap-flow.js:2262:34)
    at TLSSocket.<anonymous> (node_modules/imapflow/lib/imap-flow.js:1044:26)
    at Object.onceWrapper (events.js:416:28)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1498:12)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at TLSSocket._finishInit (_tls_wrap.js:917:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12)
```
**To Reproduce**
1. Install version 1.0.47
2. Create an instance with a custom logger with the methods debug(obj), info(obj), warn(obj) and error(obj)

**Desktop (please complete the following information):**
 - OS: linux docker image node:12-alpine
 - Browser none
 - Version 1.0.47

**Comment by andris9** [comment]
Can't replicate this error, maybe it's been somehow fixed already.
