### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by steveyout** [andris9/imapflow#31]
sometimes i get this error when connecting

```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at ImapFlow.emitError (C:\Users\User\WebstormProjects\tmail\node_modules\imapflow\lib\imap-flow.js:257:14)
    at TLSSocket._socketError._socketError.err (C:\Users\User\WebstormProjects\tmail\node_modules\imapflow\lib\imap-flow.js:491:22)
    at TLSSocket.emit (events.js:203:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)```

**Comment by andris9** [comment]
This is TCP so connection errors are normal. Just reconnect and retry your operation.

**Comment by steveyout** [comment]
ok thanks
