### ISSUE TITLE
Imaflow crashes with unhandled error when trying to connect using same client twice

### ISSUE THREAD

**Issue by shunkica** [andris9/imapflow#41]
**Describe the bug**
The program crashes when trying to connect a second time using the same client.

**To Reproduce**
1. connect
2. logout
3. connect again

**Additional context**
```
...
{"level":20,"time":1615471050885,"pid":12546,"hostname":"pcname","component":"imap-connection","cid":"sal0zyhx49p8x66bu6fd","src":"s","msg":"6 OK Logout completed (0.001 + 0.000 secs).","cid":"sal0zyhx49p8x66bu6fd"}
{"level":30,"time":1615471050915,"pid":12546,"hostname":"pcname","component":"imap-connection","cid":"sal0zyhx49p8x66bu6fd","src":"connection","msg":"Established secure TCP connection","cid":"sal0zyhx49p8x66bu6fd","secure":true,"host":"server1.example.com","servername":"server1.example.com","port":993,"address":"<server ip>","localAddress":"<my ip>","localPort":36184,"authorized":true,"algo":"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","version":"TLSv1.2"}
{"level":50,"time":1615471050919,"pid":12546,"hostname":"pcname","component":"imap-connection","cid":"sal0zyhx49p8x66bu6fd","err":{"type":"NodeError","message":"write after end","stack":"Error [ERR_STREAM_WRITE_AFTER_END]: write after end\n    at writeAfterEnd (_stream_writable.js:266:14)\n    at ImapStream.Writable.write (_stream_writable.js:315:5)\n    at TLSSocket.ondata (_stream_readable.js:718:22)\n    at TLSSocket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:297:12)\n    at readableAddChunk (_stream_readable.js:272:9)\n    at TLSSocket.Readable.push (_stream_readable.js:213:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)","code":"ERR_STREAM_WRITE_AFTER_END"},"cid":"sal0zyhx49p8x66bu6fd"}
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:266:14)
    at ImapStream.Writable.write (_stream_writable.js:315:5)
    at TLSSocket.ondata (_stream_readable.js:718:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on ImapFlow instance at:
    at ImapFlow.emitError (/home/username/DevProjects/WebstormProjects/projectname/node_modules/.pnpm/imapflow@1.0.53/node_modules/imapflow/lib/imap-flow.js:257:14)
    at ImapStream.<anonymous> (/home/username/DevProjects/WebstormProjects/projectname/node_modules/.pnpm/imapflow@1.0.53/node_modules/imapflow/lib/imap-flow.js:252:18)
    at ImapStream.emit (events.js:326:22)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at writeAfterEnd (_stream_writable.js:268:3)
    at ImapStream.Writable.write (_stream_writable.js:315:5)
    [... lines matching original stack trace ...]
    at readableAddChunk (_stream_readable.js:272:9) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

Sample code:

```
const client = new ImapFlow({
    host: keys.mailHost,
    port: keys.mailPort,
    secure: true,
    auth: {
        user: keys.mailUser,
        pass: keys.mailPass
    }
});

(async function() {
    await client.connect();
    await client.logout();
    await client.connect();
}())
```

**Comment by andris9** [comment]
You have to create a new connection object for each connection. Once connection is lost you can't reuse it.
