### ISSUE TITLE
Client hangs on logout when there is no connection to server

### ISSUE THREAD

**Issue by shunkica** [andris9/imapflow#44]
**Version**
imapflow 1.0.56

**Behavior:**
If the client fails to connect to server for some reason, then `await client.logout()` will hang indefinitely

**Expected behavior:**
The method should detect there was no connection to logout from in the first place, or it should reject the promise after a reasonable amount of time (eg. using Promise.race)

**Sample code:**
```
const {ImapFlow} = require("imapflow");

const runMailTask = async () => {
    const client = new ImapFlow({
        host: "not.a.real.dns.name.example"
    });

    try {
        await client.connect();
    } catch (err) {
        console.error("ERROR:", err)
    } finally {
        try {
            await client.logout();
            console.log("Logged out") // <- code never reaches here
        } catch (err) {
            console.error("ERROR: (logout):", err) // <- code never reaches here
            client.close();
        }
    }
};

(async function () {
    await runMailTask();
    console.log("Finished mail task") // <- code never reaches here
}())
```

**Output:**
```
{"level":50,"time":1619772740057,"pid":10854,"hostname":"shunkica","component":"imap-connection","cid":"46jsai1b3yunt8rr5w1j","err":{"type":"Error","message":"getaddrinfo ENOTFOUND not.a.real.dns.name.example","stack":"Error: getaddrinfo ENOTFOUND not.a.real.dns.name.example\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)","errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"not.a.real.dns.name.example"},"cid":"46jsai1b3yunt8rr5w1j"}
ERROR: Error: getaddrinfo ENOTFOUND not.a.real.dns.name.example
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'not.a.real.dns.name.example'
}
{"level":20,"time":1619772740065,"pid":10854,"hostname":"shunkica","component":"imap-connection","cid":"46jsai1b3yunt8rr5w1j","src":"s","msg":"1 LOGOUT","cid":"46jsai1b3yunt8rr5w1j"}
```

**To handle this I need to do something like this which seems convoluted for such a simple task:**
`await Promise.race([client.logout(), new Promise((_, reject) => setTimeout(() => reject("Timed out"), 5000))]);`

**Comment by andris9** [comment]
Fixed in v1.0.57

**Comment by Diwanshumidha** [comment]
Still Happening in v1.0.164

**Comment by Shu-Ji** [comment]
Every method hangs in my application 1.0.169.

```ts
await client.connect()
await client.logout()
await client.status()
…
```

try catch not work. It can't reach the `catch` block

**Comment by odubuc** [comment]
I experiment the same issue on `1.0.174` with wrong credentials making a clean exit difficult.
