### ISSUE TITLE
Unable to catch the ECONNRESET error

### ISSUE THREAD

**Issue by gsommavilla** [andris9/imapflow#47]
I am not able to catch the `ECONNRESET` error.

I have prepared a stripped down version of my code (since the error is
not easily replicable, also the code I am actually using is large)
and it is shown below.

In there, I simulate errors emitted by `client` and they are caught (see commented lines).
But when an actual `ECONNRESET` occurs, it is not caught (and the server crashes).

```
'use strict';

const pino = require('pino')();
pino.level = 'silent';
//pino.level = 'info';

const fs = require('fs');
const { ImapFlow } = require('imapflow');

//const rawConfigData = JSON.parse(fs.readFileSync('imapGmailConfig.json'));
const rawConfigData = JSON.parse(fs.readFileSync('imapPecConfig.json'));
rawConfigData.logger = pino;

const main = async () => {
  for (let i = 0; i < 50; i++) {
    let lock;
    let client;
    try {
      console.log("new ImapFlow");
      client = new ImapFlow(rawConfigData);
      await client.connect();

      lock = await client.getMailboxLock('INBOX');
      
      console.log("INFO: start fetching message");
      let msg = await client.fetchOne('*', { envelope: true });

      // error simulation here --> gets caught by the catch below with console.error("ERROR here1:", err);
      //
      // if (i==2) {
      //   client.emit('error', new Error('ECONNRESET'));
      // }
      
    } catch(err) {
      console.error("ERROR here1:", err);
      
    } finally {
      console.log("releasing: lock.release()");
      lock.release();
    }

    // another error simulation here --> gets caught by the catch
    // below at the line with main().catch(err => console.error("ERROR here0: ", err));
    //
    // if (i==4) {
    //   client.emit('error', new Error('ECONNRESET'));
    // }
      
    console.log("await client.logout():");
    await client.logout();
  }
};

main().catch(err => console.error("ERROR here0: ", err));
```

Actual ECONNRESET error is like this:

```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on ImapFlow instance at:
    at ImapFlow.emitError (/home/giacomo/imapflow_examples/node_modules/imapflow/lib/imap-flow.js:257:14)
    at TLSSocket._socketError (/home/giacomo/imapflow_examples/node_modules/imapflow/lib/imap-flow.js:495:22)
    at TLSSocket.emit (events.js:326:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

I am using imapflow version 1.0.57.
How can I improve my code to catch `ECONNRESET`?

Any help is very appreciated, thanks.

---
**EDIT**: It seems that the error is raising (mostly) when trying to do `client.logout()`.

**Comment by andris9** [comment]
You are supposed to have an error handler set for client, see [here](https://imapflow.com/module-imapflow-ImapFlow.html#event:error)
